export {post_register} from "./post_register.ts"
export {post_login} from "./post_login.ts"
export {get_admin} from "./get_admin.ts"
export * as restApi from "./rest_items.ts"
// export {get_login} from "./get_login.ts"