image:
  file: .gitpod.Dockerfile


tasks:
  - name: Startup
    command: sh ./scripts/startup.sh
    
  - command: |
      deno run --allow-net --unstable main.ts

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - "denoland.vscode-deno"