image:
  file: .gitpod.Dockerfile


tasks:
  - command: |
      deno run --allow-net --unstable main.ts

ports:
  - port: 8080
    onOpen: open-preview
  - port: 33060
    onOpen: ignore
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - "denoland.vscode-deno"
